# Generated by Django 3.2.5 on 2021-07-10 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Информация', 'verbose_name_plural': 'Информация'},
        ),
    ]
